### ISSUE TITLE
Connection between python server and s3_playback inconsistent

### ISSUE THREAD

**Issue by blim012** [CS179J-Team08/CS179J-Team08-Project#3]
Occasionally, cloud_sound will not begin listening to the python server until a data packet is sent from the python server to cloud_sound. cloud_sound will not output the "Listening to python server" console text on such occasions, until the packet is received from the python server
This results in only a part of the data packet being successfully received by cloud_sound.

**Comment by Arent128** [comment]
The issue might lie in the message that is initially sent from the server to the audio_engine program for acknowledgment. It waits to receive a certain length of a character stream, and if the actual incoming message is smaller than the specified length it will keep waiting for more characters in the stream. As to why the result data packet received is only partially received since the first read call consumed a portion of the packet. I'll look to see if a loss of data is occurring on the stream.

**Comment by jdicarlantonio** [comment]
Another issue that seems to be related is communication between the server and cloudsound application is inconsistent. I just ran into an issue where the data packet was not fully transferred over to the cloudsound application.

The data packet showed up complete on the server's console output, however the string packet showed to be cutoff after the userID array on the cloudsound application console output. This caused a seg fault.

After rerunning the server and application and it worked fine.

**Comment by Arent128** [comment]
So this confirms my initial suspicion that the packet data can be lost through the sockets. Meaning that in order for us to have a solid line of communication, we need to ensure that the packet is fully received before doing any other operation. I will be adding the bug label to the issue.

**Comment by Arent128** [comment]
I should have the issue fixed with my next pull request. Closing this issue down.
